name: Deploy Fabric Items

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Azure Login using Service Principal
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true   # Needed for Fabric (not subscription-scoped)

    - name: Deploy Fabric Items
      run: |
        pip install --upgrade fabric-cicd --user
        export PATH=$PATH:$HOME/.local/bin
        fabric-cicd deploy --workspace "<Fabric-Workspace-ID>" --repository_directory . --branch main
