name: Deploy to Microsoft Fabric

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Authenticate with Power BI CLI (Service Principal)
        run: |
          npx powerbi-cli login \
            --service-principal \
            --client-id "${{ secrets.CLIENT_ID }}" \
            --client-secret "${{ secrets.CLIENT_SECRET }}" \
            --tenant "${{ secrets.TENANT_ID }}"

      - name: Deploy PBIX report
        run: |
          npx powerbi-cli import report \
            --workspace-id "${{ secrets.WORKSPACE_ID }}" \
            --name "My Deployed Report" \
            --file "reports/my_report.pbix" \
            --conflict "CreateOrOverwrite"
