name: Deploy to Microsoft Fabric

on:
  push:
    branches:
      - main  # Or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js (required for Power BI CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or latest LTS

      - name: Install Power BI CLI
        run: npm install -g powerbi-cli

      - name: Authenticate with Service Principal
        run: |
          pbi login \
            --service-principal \
            --client-id "${{ secrets.CLIENT_ID }}" \
            --client-secret "${{ secrets.CLIENT_SECRET }}" \
            --tenant "${{ secrets.TENANT_ID }}"

      - name: Deploy PBIX report to Fabric
        run: |
          pbi import report \
            --workspace-id "${{ secrets.WORKSPACE_ID }}" \
            --name "My Deployed Report" \
            --file "reports/my_report.pbix" \
            --conflict "CreateOrOverwrite"
