name: Deploy PBIX to Power BI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        

      - name: Import PBIX to workspace
        shell: pwsh
        run: |
          # Install and import module
          Install-Module -Name MicrosoftPowerBIMgmt.Reports -Force -Scope CurrentUser
          Import-Module MicrosoftPowerBIMgmt.Reports
          
          # Authenticate
          $secpasswd = ConvertTo-SecureString "<CLIENT_SECRET>" -AsPlainText -Force
          $mycreds = New-Object System.Management.Automation.PSCredential ("<CLIENT_ID>", $secpasswd)
          Connect-PowerBIServiceAccount -ServicePrincipal -Credential $mycreds -Tenant "<TENANT_ID>"
          
          # Import (publish) the report using New-PowerBIReport
          New-PowerBIReport -Path "reports/SUPERSTORE.pbix" -WorkspaceId "<WORKSPACE_ID>" -Name "My Deployed Report" -ConflictAction CreateOrOverwrite

              shell: pwsh
