name: Deploy to Microsoft Fabric

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET SDK (required for Power BI CLI)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # Or 8.0.x if supported

      - name: Install Power BI CLI
        run: |
          dotnet tool install --global Microsoft.PowerBI.CLI
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          pbi --version

      - name: Authenticate with Service Principal
        run: |
          pbi login \
            --service-principal \
            --client-id "${{ secrets.CLIENT_ID }}" \
            --client-secret "${{ secrets.CLIENT_SECRET }}" \
            --tenant "${{ secrets.TENANT_ID }}"

      - name: Deploy PBIX file
        run: |
          pbi import report \
            --workspace-id "${{ secrets.WORKSPACE_ID }}" \
            --name "My Deployed Report" \
            --file "reports/my_report.pbix" \
            --conflict "CreateOrOverwrite"
