name: Deploy PBIX to Power BI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Power BI PowerShell module
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser
          Import-Module MicrosoftPowerBIMgmt.Reports
        shell: pwsh

      - name: Login using Service Principal
        run: |
          $secpasswd = ConvertTo-SecureString "${{ secrets.CLIENT_SECRET }}" -AsPlainText -Force
          $mycreds = New-Object System.Management.Automation.PSCredential ("${{ secrets.CLIENT_ID }}", $secpasswd)
          Connect-PowerBIServiceAccount -ServicePrincipal -Credential $mycreds -Tenant "${{ secrets.TENANT_ID }}"
        shell: pwsh

      - name: Import PBIX to workspace
        run: |
          Import-PowerBIReport `
            -Path "reports/SUPERSTORE.pbix" `
            -WorkspaceId "${{ secrets.WORKSPACE_ID }}" `
            -Name "My Deployed Report" `
            -ConflictAction CreateOrOverwrite
        shell: pwsh
