name: Deploy to Microsoft Fabric

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Power BI CLI
        run: |
          curl -L https://aka.ms/pbi-tools-cli-linux -o pbi
          chmod +x pbi
          sudo mv pbi /usr/local/bin/pbi
          pbi --version

      - name: Authenticate with Service Principal
        run: |
          pbi login \
            --service-principal \
            --client-id "${{ secrets.CLIENT_ID }}" \
            --client-secret "${{ secrets.CLIENT_SECRET }}" \
            --tenant "${{ secrets.TENANT_ID }}"

      - name: Deploy PBIX file
        run: |
          pbi import report \
            --workspace-id "${{ secrets.WORKSPACE_ID }}" \
            --name "My Deployed Report" \
            --file "reports/my_report.pbix" \
            --conflict "CreateOrOverwrite"
