name: Deploy to Microsoft Fabric

on:
  push:
    branches:
      - main   # Change if you want another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo files (PBIX / Notebooks / Pipelines, etc.)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Install Power BI CLI
      - name: Install Power BI CLI
        run: |
          npm install -g powerbi-cli

      # 3️⃣ Authenticate with Service Principal
      - name: Authenticate with Service Principal
        run: |
          pbi login \
            --service-principal \
            --client-id ${{ secrets.CLIENT_ID }} \
            --client-secret ${{ secrets.CLIENT_SECRET }} \
            --tenant ${{ secrets.TENANT_ID }}

      # 4️⃣ (Optional Test) List Workspaces to confirm login works
      - name: List Workspaces
        run: |
          pbi workspace list

      # 5️⃣ Deploy PBIX Report
      - name: Deploy PBIX Report
        run: |
          pbi import report \
            --workspace-id ${{ secrets.WORKSPACE_ID }} \
            --name "SUPERSTORE" \
            --file "reports/SUPERSTORE.pbix" \
            --conflict "CreateOrOverwrite"

      # 6️⃣ (Optional) Refresh Dataset
      - name: Refresh Dataset
        run: |
          pbi dataset refresh \
            --workspace-id ${{ secrets.WORKSPACE_ID }} \
            --dataset-id ${{ secrets.DATASET_ID }}
