name: Deploy to Microsoft Fabric

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or latest LTS version

      - name: Install Power BI CLI globally
        run: |
          npm install -g @microsoft/powerbi-cli
          echo "$(npm bin -g)" >> $GITHUB_PATH
          which pbi
          pbi --version

      - name: Authenticate with Service Principal
        run: |
          pbi login \
            --service-principal \
            --client-id "${{ secrets.CLIENT_ID }}" \
            --client-secret "${{ secrets.CLIENT_SECRET }}" \
            --tenant "${{ secrets.TENANT_ID }}"

      - name: Deploy PBIX file
        run: |
          pbi import report \
            --workspace-id "${{ secrets.WORKSPACE_ID }}" \
            --name "My Deployed Report" \
            --file "reports/my_report.pbix" \
            --conflict "CreateOrOverwrite"
