name: Publish to Fabric

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fabric_cicd

      - name: Run Fabric Publish Script
        env:
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
          FABRIC_REPO_DIR: .
          FABRIC_ITEM_TYPES: Notebook,DataPipeline,Environment
          AZURE_TENANT_ID: ${{ secrets.TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: python fabric_publish.py
